version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: pnlinh/app
    volumes:
      - .:/var/www/html
    ports:
      - ${DOCKER_APP_PORT}:80
    networks:
      - localnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: pnlinh/node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["node"]
    command: echo hi
    networks:
      - localnet
  mysql:
    image: mysql:5.7
    ports:
      - ${DOCKER_DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - localnet
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - localnet
networks:
  localnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
